project_id = "oxoqqrpholocoxkizbfa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "https://lovableproject.com"
additional_redirect_urls = ["https://lovableproject.com"]
jwt_expiry = 3600
enable_signup = true

[functions.admin-auth]
verify_jwt = false