// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxoqqrpholocoxkizbfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94b3FxcnBob2xvY294a2l6YmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzU2NTIsImV4cCI6MjA3NDMxMTY1Mn0.Soet7j_tT4E3kUye7OSotLWfTXA9qyWES2xjvh68SfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});